/**
 * All of the code here is generated by a free-trial of Claude I was
 * granted. While I feel sick to my stomach saying that and even when
 * using it, I would've probably ripped out all of my hair & skin
 * trying to go at this myself, and this project wouldn't go anywhere
 * without it. As much as I praise hand-written code and still do it
 * for stuff that isn't as complex as this, I had to give in
 * (HOPEFULLY) just this one time.
 * 
 * I tried to make sure Claude did not make this script work only for
 * BFPROFEditor and only made it work on this single script--no edits
 * to any other file. If you wanna use this for yourself, then go at
 * it I guess lol.
 * 
 * -ktg5 2026
 */


export type ProfSetting = {
    name: string;
    typeId: number;
    value: string;
    isBlob: boolean;

    setSettingValue: typeof setSettingValue,
    setSettingBytes: typeof setSettingBytes,

    _tag: Uint8Array;
    _rawName: Uint8Array;   // [4-byte name_length LE32][name bytes incl. null]
    _typeTag: Uint8Array;   // [4-byte type_tag LE32]; empty for inline-blob entries (tag=0x05)
    _rawValue: Uint8Array;  // text: value bytes + null; blob: [4-byte len LE32][raw bytes]
};

type BFSection = {
    countBytes: Uint8Array; // recalculated on serialize
    hashBytes: Uint8Array;  // 4 bytes for BF6 hash-prefixed sections; empty otherwise
    entries: ProfSetting[];
};


function setSettingValue(setting: ProfSetting, value: string): void {
    setting.value = value;
}

function setSettingBytes(setting: ProfSetting, bytes: Uint8Array): void {
    const end = bytes.length > 0 && bytes[bytes.length - 1] === 0x00
        ? bytes.length - 1
        : bytes.length;
    setting.value = new TextDecoder('ascii').decode(bytes.subarray(0, end));
}

function arrayEquals(a: Uint8Array, b: Uint8Array): boolean {
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) {
        if (a[i] !== b[i]) return false;
    }
    return true;
}


export class BFPROF {
    private buffer: Uint8Array;
    private offset: number;
    private decoder: TextDecoder;
    private encoder: TextEncoder;
    private version = "";
    private _fileHeader: Uint8Array;
    private _sections: BFSection[];
    private _trailingZeros: Uint8Array;

    constructor(buffer: Uint8Array) {
        if (!(buffer instanceof Uint8Array)) throw new Error("Input must be a Uint8Array");
        this.buffer = buffer;
        this.offset = 0;
        this.decoder = new TextDecoder('ascii');
        this.encoder = new TextEncoder();
        this._fileHeader = new Uint8Array(0);
        this._sections = [];
        this._trailingZeros = new Uint8Array(0);
    }

    private readLE32(): number {
        const v = this.buffer[this.offset]
                | (this.buffer[this.offset + 1] << 8)
                | (this.buffer[this.offset + 2] << 16)
                | (this.buffer[this.offset + 3] << 24);
        this.offset += 4;
        return v >>> 0;
    }

    private parseEntry(): ProfSetting {
        // tag_field (4 bytes, value 0x01, 0x02, 0x04, etc.; 0x05 signals inline-blob format)
        const tagStart = this.offset;
        const tagValue = this.readLE32();
        const _tag = this.buffer.subarray(tagStart, this.offset) as Uint8Array;

        // name_length (4 bytes LE32) + name bytes (incl. null terminator)
        const nameLenStart = this.offset;
        const nameLength = this.readLE32();
        const nameDataStart = this.offset;
        const nameDataEnd = this.offset + nameLength;
        const _rawName = this.buffer.subarray(nameLenStart, nameDataEnd) as Uint8Array;
        const name = this.decoder.decode(this.buffer.subarray(nameDataStart, nameDataEnd - 1));
        this.offset = nameDataEnd;

        // tag=0x05 means inline-blob: [name_len][name][value_len][value_bytes], no separate type_tag.
        // BF4's PresenceStateTelemetryToken uses this format.
        if (tagValue === 0x05) {
            const valueStart = this.offset;
            const valueLen = this.readLE32();
            this.offset += valueLen;
            const _rawValue = this.buffer.subarray(valueStart, this.offset) as Uint8Array;
            return { name, typeId: 0x05, value: '', isBlob: true, setSettingValue, setSettingBytes, _tag, _rawName, _typeTag: new Uint8Array(0), _rawValue };
        }

        // type_tag (4 bytes LE32, byte 0 = type ID)
        const typeTagStart = this.offset;
        this.readLE32();
        const _typeTag = this.buffer.subarray(typeTagStart, this.offset) as Uint8Array;
        const typeId = this.buffer[typeTagStart];

        let value = "";
        let isBlob = false;
        let _rawValue: Uint8Array;

        if (typeId === 0x05 && this.version !== '6') {
            // Binary blob (BF4/BF1/BF2042 only): 4-byte explicit value_length followed by raw bytes.
            // In BF6 hash-prefixed sections, type 0x05 is a null-terminated integer string instead.
            const valueStart = this.offset;
            const valueLen = this.readLE32();
            this.offset += valueLen;
            _rawValue = this.buffer.subarray(valueStart, this.offset) as Uint8Array;
            isBlob = true;
        } else {
            // Null-terminated ASCII value
            const valueStart = this.offset;
            while (this.offset < this.buffer.length && this.buffer[this.offset] !== 0x00) {
                this.offset++;
            }
            this.offset++; // consume null terminator
            _rawValue = this.buffer.subarray(valueStart, this.offset) as Uint8Array;
            value = this.decoder.decode(this.buffer.subarray(valueStart, this.offset - 1));
        }

        return { name, typeId, value, isBlob, setSettingValue, setSettingBytes, _tag, _rawName, _typeTag, _rawValue };
    }

    public parse(): ProfSetting[] {
        if (this.buffer.length < 54) throw new Error('PROFSAVE is not valid');

        this._sections = [];
        this.version = "";

        // Version / game detection
        if (this.decoder.decode(this.buffer.subarray(0, 8)) === "FBCHUNKS") {
            const gameId = this.buffer.subarray(18, 23);
            if (arrayEquals(gameId, new Uint8Array([0xe1, 0xf0, 0xb2, 0x4f, 0x0e]))) {
                this.version = '6';
            } else if (arrayEquals(gameId, new Uint8Array([0x0f, 0x5f, 0x07, 0x5d, 0x0d]))) {
                this.version = '2042';
            } else if (arrayEquals(gameId, new Uint8Array([0x91, 0x8f, 0x1f, 0xda, 0x16]))) {
                this.version = '1';
            }
        } else if (arrayEquals(this.buffer.subarray(0, 4), new Uint8Array([0x3a, 0xe4, 0x29, 0x41]))) {
            this.version = '4';
        }

        if (!this.version) throw new Error('PROFSAVE is not valid');

        // Slice off the file header (everything before the first section count)
        let fileHeaderEnd: number;
        switch (this.version) {
            case '4':    fileHeaderEnd = 20; break; // 0x14
            case '1':
            case '2042': fileHeaderEnd = 42; break; // 0x2A
            default:     fileHeaderEnd = 54; break; // 0x36 (BF6)
        }
        this._fileHeader = this.buffer.subarray(0, fileHeaderEnd) as Uint8Array;
        this.offset = fileHeaderEnd;

        if (this.version === '6') {
            // BF6: outer blobs use a different 5-field format:
            //   [type_indicator:4][name_len:4][name][data_len:4][data]
            // They can't be parsed by parseEntry() (which expects a separate type_tag after name).
            // Skip them and fold into _fileHeader so they're preserved opaquely.
            const outerCount = this.readLE32();
            for (let i = 0; i < outerCount; i++) {
                this.offset += 4; // type indicator (05 00 00 00)
                const nameLen = this.readLE32();
                this.offset += nameLen;
                const dataLen = this.readLE32();
                this.offset += dataLen;
            }
            this._fileHeader = this.buffer.subarray(0, this.offset) as Uint8Array;

            // BF6 subsequent sections: [4-byte hash][4-byte count][entries]
            while (this.offset + 4 <= this.buffer.length) {
                const hashStart = this.offset;
                const hash = this.readLE32();
                if (hash === 0) {
                    this.offset -= 4; // trailing zeros start here
                    break;
                }
                const hashBytes = this.buffer.subarray(hashStart, hashStart + 4) as Uint8Array;

                if (this.offset + 4 > this.buffer.length) { this.offset -= 4; break; }
                const countStart = this.offset;
                const count = this.readLE32();
                const countBytes = this.buffer.subarray(countStart, this.offset) as Uint8Array;

                const entries: ProfSetting[] = [];
                for (let i = 0; i < count; i++) {
                    entries.push(this.parseEntry());
                }
                this._sections.push({ countBytes, hashBytes, entries });
            }
        } else {
            // BF4 / BF1 / BF2042: plain [count][entries] sections, repeating
            while (this.offset + 4 <= this.buffer.length) {
                const countStart = this.offset;
                const count = this.readLE32();
                const countBytes = this.buffer.subarray(countStart, this.offset) as Uint8Array;

                if (count === 0) {
                    // Peek next 4 bytes: if also zero, we've hit trailing zero padding
                    if (this.offset + 4 > this.buffer.length) {
                        this.offset -= 4;
                        break;
                    }
                    const nextVal = (this.buffer[this.offset]
                                   | (this.buffer[this.offset + 1] << 8)
                                   | (this.buffer[this.offset + 2] << 16)
                                   | (this.buffer[this.offset + 3] << 24)) >>> 0;
                    if (nextVal === 0) {
                        this.offset -= 4; // include the zero count in trailing zeros
                        break;
                    }
                    // Valid empty section placeholder (BF1 has one mid-file)
                    this._sections.push({ countBytes, hashBytes: new Uint8Array(0), entries: [] });
                } else {
                    // Sanity check: a valid count must fit in the remaining buffer
                    // (each entry is at minimum 8 bytes: 4-byte tag + 4-byte name_len)
                    if (count * 8 > this.buffer.length - this.offset) {
                        this.offset -= 4; // back up so this garbage count lands in _trailingZeros
                        break;
                    }
                    const entries: ProfSetting[] = [];
                    for (let i = 0; i < count; i++) {
                        entries.push(this.parseEntry());
                    }
                    this._sections.push({ countBytes, hashBytes: new Uint8Array(0), entries });
                }
            }
        }

        this._trailingZeros = this.buffer.subarray(this.offset) as Uint8Array;

        return this._sections
            .flatMap(s => s.entries)
            .filter(e => !e.isBlob && e.name.length > 0);
    }

    public serialize(): Uint8Array {
        const chunks: Uint8Array[] = [this._fileHeader];

        for (const section of this._sections) {
            if (section.hashBytes.length > 0) chunks.push(section.hashBytes);

            // Recalculate the count in case entries were added or removed
            const c = section.entries.length;
            const cb = new Uint8Array(4);
            cb[0] = c & 0xff;
            cb[1] = (c >>> 8) & 0xff;
            cb[2] = (c >>> 16) & 0xff;
            cb[3] = (c >>> 24) & 0xff;
            chunks.push(cb);

            for (const entry of section.entries) {
                chunks.push(entry._tag, entry._rawName);
                if (entry._typeTag.length > 0) chunks.push(entry._typeTag);
                if (entry.isBlob) {
                    chunks.push(entry._rawValue); // length prefix + raw bytes, unchanged
                } else {
                    const enc = this.encoder.encode(entry.value);
                    const val = new Uint8Array(enc.length + 1); // +1 for null terminator
                    val.set(enc);
                    chunks.push(val);
                }
            }
        }

        chunks.push(this._trailingZeros);

        const total = chunks.reduce((sum, chunk) => sum + chunk.length, 0);
        const out = new Uint8Array(total);
        let pos = 0;
        for (const chunk of chunks) { out.set(chunk, pos); pos += chunk.length; }
        return out;
    }
}
